### ISSUE TITLE
Onboard translators should return a consistent response format for authentication

### ISSUE THREAD

**Issue by busadave13** [openT2T/onboarding#18]
Wink and Nest return a different response format for authentication (See Below). Translators should get the response from the hub and return a consistent format. Although the 'accessToken' property is consistent between Wink & Nest there could be other hubs that use a different name to represent the acccessToken and this could cause issues for callers that are caching the response.

Nest
{
  "accessToken": "token",
  "ttl": 0
}

Wink
{
  "accessToken": "",
  "refreshToken": "",
  "tokenType": "",
  "scopes": ""
}

**Comment by arjun-msft** [comment]
Given the varying information per onboarder this can not be consistent at this level, we can wrap it but in my opinion this provides little value at the moment.  I do however expect this to change as we work out the other onboarding scenarios.

**Comment by danielrischar** [comment]
#29
