### ISSUE TITLE
index.js in org.OpenT2T.Onboarding.WinkHub fails to load

### ISSUE THREAD

**Issue by busadave13** [openT2T/onboarding#9]
Cloned the repo and opened org.OpenT2T.Onboarding.WinkHub VS Code, tried to run test.js but the script failed to load index.js for invalid token. From what I could tell this was due to the use of the lambda expressions in the following lines

line 95: var req = https.request(postOptions, (res) => {
line 200: req.on('error', (e) => {

I removed the lambda and added function and was able to successfully run test.js

**Comment by jasongin** [comment]
You must be running a very old version of Node.js. Recent versions (>= 4 I think) definitely support arrow lambdas.

(BTW, the `this` binding semantics are different from a function, so changing an arrow lambda to a function isn't guaranteed to work.)

**Comment by busadave13** [comment]
That was it, was definitely a very old version of node. Everything works great now. Thanks for the quick response and feedback
